apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-router-service
  namespace: avalanche-network
  labels:
    app: message-router-service
    tier: network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-router-service
  template:
    metadata:
      labels:
        app: message-router-service
        tier: network
    spec:
      containers:
      - name: message-router
        image: avalanche/message-router:v1.0.0
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: PORT
          value: "8085"
        - name: REDIS_URL
          value: "redis://cache-service.avalanche-storage.svc.cluster.local:6379"
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: message-router-service
  namespace: avalanche-network
  labels:
    app: message-router-service
    tier: network
spec:
  selector:
    app: message-router-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: message-router-hpa
  namespace: avalanche-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: message-router-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: message-router-pdb
  namespace: avalanche-network
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: message-router-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-router-config
  namespace: avalanche-network
data:
  config.yaml: |
    message_router:
      max_message_size: 10MB
      routing_timeout: 30s
      queue_size: 1000
      
    websocket:
      max_connections: 1000
      ping_interval: 30s
      pong_timeout: 10s
      
    redis:
      pool_size: 10
      idle_timeout: 300s
      
    routing_rules:
      - source: "consensus"
        targets: ["vm-manager", "chain-manager", "validator"]
      - source: "p2p-network"
        targets: ["consensus", "validator"]
      - source: "validator"
        targets: ["consensus", "p2p-network"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: message-router-network-policy
  namespace: avalanche-network
spec:
  podSelector:
    matchLabels:
      app: message-router-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: avalanche-core
    - namespaceSelector:
        matchLabels:
          name: avalanche-network
    - namespaceSelector:
        matchLabels:
          name: avalanche-gateway
    ports:
    - protocol: TCP
      port: 8085
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: avalanche-storage
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53 