apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-manager-service
  namespace: avalanche-network
  labels:
    app: peer-manager-service
    tier: network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peer-manager-service
  template:
    metadata:
      labels:
        app: peer-manager-service
        tier: network
    spec:
      containers:
      - name: peer-manager
        image: avalanche/peer-manager:v1.0.0
        ports:
        - containerPort: 8086
          name: http
        env:
        - name: PORT
          value: "8086"
        - name: MAX_PEERS
          value: "100"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_URL
          value: "redis://cache-service.avalanche-storage.svc.cluster.local:6379"
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: peer-manager-service
  namespace: avalanche-network
  labels:
    app: peer-manager-service
    tier: network
spec:
  selector:
    app: peer-manager-service
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: peer-manager-hpa
  namespace: avalanche-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peer-manager-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: peer-manager-pdb
  namespace: avalanche-network
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: peer-manager-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-manager-config
  namespace: avalanche-network
data:
  config.yaml: |
    peer_manager:
      max_peers: 100
      peer_timeout: 300s
      discovery_interval: 60s
      maintenance_interval: 120s
      
    peer_scoring:
      latency_weight: 0.3
      uptime_weight: 0.5
      validator_weight: 0.2
      
    connection_limits:
      max_inbound: 50
      max_outbound: 50
      connection_timeout: 30s
      
    discovery:
      bootstrap_nodes:
        - "bootstrap1.avalanche.network:9651"
        - "bootstrap2.avalanche.network:9651"
      discovery_timeout: 10s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: peer-manager-network-policy
  namespace: avalanche-network
spec:
  podSelector:
    matchLabels:
      app: peer-manager-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: avalanche-core
    - namespaceSelector:
        matchLabels:
          name: avalanche-network
    - namespaceSelector:
        matchLabels:
          name: avalanche-gateway
    ports:
    - protocol: TCP
      port: 8086
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: avalanche-storage
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 9651 