apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-manager-service
  namespace: avalanche-core
  labels:
    app: chain-manager-service
    tier: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chain-manager-service
  template:
    metadata:
      labels:
        app: chain-manager-service
        tier: core
    spec:
      containers:
      - name: chain-manager
        image: avalanche/chain-manager:v1.0.0
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: PORT
          value: "8082"
        - name: DB_HOST
          value: "state-database.avalanche-storage.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: DB_NAME
          value: "avalanche_chains"
        - name: REDIS_URL
          value: "redis://cache-service.avalanche-storage.svc.cluster.local:6379"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: chain-manager-service
  namespace: avalanche-core
  labels:
    app: chain-manager-service
    tier: core
spec:
  selector:
    app: chain-manager-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chain-manager-hpa
  namespace: avalanche-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chain-manager-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chain-manager-pdb
  namespace: avalanche-core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chain-manager-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chain-manager-config
  namespace: avalanche-core
data:
  config.yaml: |
    chain_manager:
      max_chains: 100
      chain_timeout: 30s
      sync_interval: 10s
      
    database:
      max_connections: 50
      connection_timeout: 30s
      query_timeout: 60s
      
    cache:
      ttl: 3600s
      max_size: 1000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chain-manager-network-policy
  namespace: avalanche-core
spec:
  podSelector:
    matchLabels:
      app: chain-manager-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: avalanche-gateway
    - namespaceSelector:
        matchLabels:
          name: avalanche-core
    ports:
    - protocol: TCP
      port: 8082
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: avalanche-storage
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53 