apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-service
  namespace: avalanche-core
  labels:
    app: validator-service
    tier: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: validator-service
  template:
    metadata:
      labels:
        app: validator-service
        tier: core
    spec:
      containers:
      - name: validator
        image: avalanche/validator:v1.0.0
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: PORT
          value: "8083"
        - name: DB_HOST
          value: "state-database.avalanche-storage.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: DB_NAME
          value: "avalanche_validators"
        - name: REDIS_URL
          value: "redis://cache-service.avalanche-storage.svc.cluster.local:6379"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: validator-service
  namespace: avalanche-core
  labels:
    app: validator-service
    tier: core
spec:
  selector:
    app: validator-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: validator-hpa
  namespace: avalanche-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: validator-service
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: validator-pdb
  namespace: avalanche-core
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: validator-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
  namespace: avalanche-core
data:
  config.yaml: |
    validator:
      max_validators: 1000
      uptime_threshold: 0.8
      monitoring_interval: 300s
      inactive_timeout: 600s
      
    staking:
      min_stake: 2000000000000 # 2000 AVAX in nAVAX
      max_stake: 3000000000000000 # 3M AVAX in nAVAX
      delegation_fee: 0.02
      
    database:
      max_connections: 50
      connection_timeout: 30s
      query_timeout: 60s
      
    cache:
      ttl: 1800s
      max_size: 2000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: validator-network-policy
  namespace: avalanche-core
spec:
  podSelector:
    matchLabels:
      app: validator-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: avalanche-gateway
    - namespaceSelector:
        matchLabels:
          name: avalanche-core
    - namespaceSelector:
        matchLabels:
          name: avalanche-network
    ports:
    - protocol: TCP
      port: 8083
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: avalanche-storage
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53 