apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-manager-service
  namespace: avalanche-core
  labels:
    app: vm-manager-service
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vm-manager-service
  template:
    metadata:
      labels:
        app: vm-manager-service
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: avalanche-service-account
      containers:
      - name: vm-manager
        image: avalanche/vm-manager:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: VM_REGISTRY_URL
          value: "http://vm-registry:8080"
        - name: MAX_VMS_PER_NODE
          value: "10"
        - name: REDIS_URL
          value: "redis://message-queue.avalanche-network:6379"
        - name: STATE_DB_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@state-database.avalanche-storage:5432/avalanche_state"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: vm-storage
          mountPath: /var/lib/vms
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: vm-storage
        persistentVolumeClaim:
          claimName: vm-storage-pvc
      - name: config
        configMap:
          name: vm-manager-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: vm-manager-service
  namespace: avalanche-core
  labels:
    app: vm-manager-service
spec:
  selector:
    app: vm-manager-service
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-storage-pvc
  namespace: avalanche-core
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-manager-config
  namespace: avalanche-core
data:
  vm-manager.yaml: |
    vmManager:
      maxVMsPerNode: 10
      vmTimeout: 60s
      registryURL: "http://vm-registry:8080"
      
    storage:
      path: "/var/lib/vms"
      maxSize: "50Gi"
      
    logging:
      level: info
      format: json
      
    metrics:
      enabled: true
      port: 8081
      path: /metrics
      
    tracing:
      enabled: true
      jaegerEndpoint: "http://jaeger.avalanche-monitoring:14268/api/traces"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vm-manager-hpa
  namespace: avalanche-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vm-manager-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60 