apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-dag-worker
  labels:
    app: avalanche-dag-worker
spec:
  replicas: 3 # Start with 3 worker pods, scale as needed
  selector:
    matchLabels:
      app: avalanche-dag-worker
  template:
    metadata:
      labels:
        app: avalanche-dag-worker
    spec:
      containers:
      - name: avalanche-dag-worker
        image: avalanche-dag-worker:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 9650
          name: worker-api
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_PROCESSING_THREADS
          value: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 9650
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9650
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: avalanche-dag-worker-service
spec:
  selector:
    app: avalanche-dag-worker
  ports:
  - name: worker-api
    port: 9650
    targetPort: 9650
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: avalanche-dag-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avalanche-dag-worker
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: avalanche-dag-worker-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: avalanche-dag-worker 