global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'avalanche-node'
    static_configs:
      - targets: ['avalanche-node:9650']
        labels:
          instance: 'avalanche-node'

  - job_name: 'workers'
    dns_sd_configs:
      - names:
          - 'worker'
        type: 'A'
        port: 9652
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: job 