global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'avalanche-node'
    static_configs:
      - targets: ['avalanche-node:9650']
        labels:
          instance: 'avalanche-node'

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9652']
        labels:
          instance: 'worker-1' 